version: '3.4'
services:
  database:
    image: "postgres"
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    command:
      - postgres -c stats_temp_directory=/tmp
  app:
    build:
      dockerfile: Dockerfile
      context: .
      # development stage only
      target: development
    volumes:
      # hot reloading
      - .:/usr/src/app
    env_file:
      - .env
    # rewrite CMD [ "node", "dist/main.js" ]
    command: yarn start:dev
    ports:
      - "8080:8080"